apiVersion: v1
kind: Template
template: pentaho
metadata:
  name: pentaho
  annotations:
    openshift.io/display-name: "Pentaho Carte server" 
    description: "A simple slave for pentaho"
    iconClass: "icon-play"
    template.openshift.io/provider-display-name: "Apartamento 101"
    template.openshift.io/documentation-url: "https://github.com/cetres/openshift-pentaho"
    tags: "pentaho,pdi,kettle,bi,carte,etl"
labels:
  app: pentaho-carte
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: pentaho
    name: ${APPLICATION_NAME}
  spec:
    tags:
      from:
        kind: DockerImage
        name: cetres/openshift-pentaho
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: pentaho
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: pentaho
      deploymentconfig: pentaho
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pentaho
          deploymentconfig: pentaho
      spec:
        containers:
        - env:
          - name: SERVER_USER
            value: admin
          - name: SERVER_PASSWD
            value: admin
          - name: SERVER_HOST
            value: 0.0.0.0
          - name: SERVER_NAME
            value: pentaho-dev.os.cna.org.br
          image: cetres/openshift-pentaho@sha256:ea67ad8c6c40dbc8fa84fa8e75c9b1dcfe914442fe176e6aeb74b64c2a19ae6f
          imagePullPolicy: Always
          name: pentaho
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/pentaho/repository
            name: pentaho-repository
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: pentaho-repository
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pentaho
        from:
          kind: ImageStreamTag
          name: pentaho-app:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: pentaho
    name: ${APPLICATION_NAME}
  spec:
    host: pentaho.os.cna.org.br
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: pentaho
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: pentaho
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: pentaho
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
